#!/bin/sh
set -eu

BI_READONLY_USER="${BI_READONLY_USER:-bi_readonly}"
BI_READONLY_PASSWORD="${BI_READONLY_PASSWORD:-bi_readonly}"

psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<EOF
DO \$\$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_roles WHERE rolname = '${BI_READONLY_USER}') THEN
        EXECUTE format('CREATE ROLE %I LOGIN PASSWORD %L', '${BI_READONLY_USER}', '${BI_READONLY_PASSWORD}');
    ELSE
        EXECUTE format('ALTER ROLE %I LOGIN PASSWORD %L', '${BI_READONLY_USER}', '${BI_READONLY_PASSWORD}');
    END IF;
END
\$\$;

GRANT CONNECT ON DATABASE ${POSTGRES_DB} TO ${BI_READONLY_USER};
EOF
