slice_name: "ABC-XYZ: Матрица выручки по строкам (%)"
description: Процентное распределение выручки по строкам ABC-XYZ, как в notebook.
certified_by: null
certification_details: null
viz_type: heatmap_v2
params:
  datasource: 1__table
  viz_type: heatmap_v2
  x_axis: xyz_sales_category
  groupby: abc_category
  metric: total_revenue_sum
  adhoc_filters: []
  row_limit: 10000
  sort_x_axis: alpha_asc
  sort_y_axis: alpha_asc
  normalize_across: y
  legend_type: continuous
  linear_color_scheme: superset_seq_1
  xscale_interval: -1
  yscale_interval: -1
  left_margin: auto
  bottom_margin: auto
  value_bounds:
    - null
    - null
  y_axis_format: SMART_NUMBER
  show_legend: true
  show_percentage: true
  show_values: true
  extra_form_data: {}
cache_timeout: null
uuid: d7b0c9ba-4d9f-49ba-b51c-b3d4ee3bc84b
version: 1.0.0
dataset_uuid: 12e7b948-21e7-4cb2-8d1a-8b078f4d9ca9
