slice_name: "ABC-XYZ: Матрица суммы показателя"
description: Корректная ABC-XYZ матрица из обновленного notebook блока abc_xyz_analysis().
certified_by: null
certification_details: null
viz_type: heatmap_v2
params:
  datasource: 1__table
  viz_type: heatmap_v2
  x_axis: xyz_category
  groupby: abc_category
  metric: total_revenue_sum
  adhoc_filters: []
  row_limit: 10000
  sort_x_axis: alpha_asc
  sort_y_axis: alpha_asc
  normalize_across: heatmap
  legend_type: continuous
  linear_color_scheme: superset_seq_1
  xscale_interval: -1
  yscale_interval: -1
  left_margin: auto
  bottom_margin: auto
  value_bounds:
    - null
    - null
  y_axis_format: SMART_NUMBER
  show_legend: true
  show_percentage: false
  show_values: true
  extra_form_data: {}
cache_timeout: null
uuid: 3cc5916b-0fdf-45ff-afb8-c6d5ca814930
version: 1.0.0
dataset_uuid: 12e7b948-21e7-4cb2-8d1a-8b078f4d9ca9
