slice_name: "ABC: Доля выручки по брендам"
description: Доля выручки по ABC-категориям брендов.
certified_by: null
certification_details: null
viz_type: pie
params:
  datasource: 10__table
  viz_type: pie
  groupby:
    - abc_category
  metric: total_revenue_sum
  adhoc_filters: []
  row_limit: 100
  sort_by_metric: true
  color_scheme: supersetColors
  show_labels_threshold: 5
  show_legend: true
  legendType: scroll
  legendOrientation: top
  label_type: key
  number_format: SMART_NUMBER
  show_labels: true
  labels_outside: true
  outerRadius: 70
  innerRadius: 30
  extra_form_data: {}
cache_timeout: null
uuid: 901650d5-7a45-4a09-82f4-172b903ff22f
version: 1.0.0
dataset_uuid: 8383f240-27a5-40a9-aa9e-a03f46c90c80
