slice_name: "ABC: Бренды по выручке"
description: Ранжирование брендов по выручке.
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  adhoc_filters: []
  bar_stacked: false
  bottom_margin: auto
  color_scheme: supersetColors
  columns: []
  contribution: false
  datasource: 10__table
  groupby:
    - brand
  metrics:
    - total_revenue_sum
  order_bars: true
  queryFields:
    columns: groupby
    groupby: groupby
    metrics: metrics
  row_limit: 20
  show_bar_value: false
  show_controls: true
  show_legend: false
  viz_type: dist_bar
  x_axis_label: Бренд
  x_ticks_layout: staggered
  y_axis_format: SMART_NUMBER
cache_timeout: null
uuid: 4b9635b0-b82c-4b75-b096-499deea13b5e
version: 1.0.0
dataset_uuid: 8383f240-27a5-40a9-aa9e-a03f46c90c80
