slice_name: "ABC: Матрица миграции категорий"
description: Матрица миграции товарных категорий между первой и последней покупкой.
certified_by: null
certification_details: null
viz_type: heatmap_v2
params:
  datasource: 8__table
  viz_type: heatmap_v2
  x_axis: last_category
  groupby: first_category
  metric: migration_percent_avg
  adhoc_filters: []
  row_limit: 10000
  sort_x_axis: alpha_asc
  sort_y_axis: alpha_asc
  normalize_across: heatmap
  legend_type: continuous
  linear_color_scheme: superset_seq_1
  xscale_interval: -1
  yscale_interval: -1
  left_margin: auto
  bottom_margin: auto
  value_bounds:
    - null
    - null
  y_axis_format: SMART_NUMBER
  show_legend: true
  show_percentage: false
  show_values: true
  extra_form_data: {}
cache_timeout: null
uuid: 85b16186-0875-4f74-b208-76f340ff563d
version: 1.0.0
dataset_uuid: 60d26ecb-35a0-43db-be3a-7af1d422d3e4
