slice_name: "ABC: Стабильность категорий"
description: Доля клиентов, оставшихся в той же товарной категории.
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  adhoc_filters: []
  bar_stacked: false
  bottom_margin: auto
  color_scheme: supersetColors
  columns: []
  contribution: false
  datasource: 8__table
  groupby:
    - first_category
  metrics:
    - category_stability_percent_avg
  order_bars: true
  queryFields:
    columns: groupby
    groupby: groupby
    metrics: metrics
  row_limit: 100
  show_bar_value: false
  show_controls: true
  show_legend: false
  viz_type: dist_bar
  x_axis_label: Начальная категория
  x_ticks_layout: staggered
  y_axis_format: SMART_NUMBER
cache_timeout: null
uuid: 24a6d4cb-999a-44aa-a74c-082936509753
version: 1.0.0
dataset_uuid: 60d26ecb-35a0-43db-be3a-7af1d422d3e4
