slice_name: "ABC: Доля выручки по категориям товаров"
description: Доля выручки по ABC-категориям товарных категорий.
certified_by: null
certification_details: null
viz_type: pie
params:
  datasource: 9__table
  viz_type: pie
  groupby:
    - abc_category
  metric: total_revenue_sum
  adhoc_filters: []
  row_limit: 100
  sort_by_metric: true
  color_scheme: supersetColors
  show_labels_threshold: 5
  show_legend: true
  legendType: scroll
  legendOrientation: top
  label_type: key
  number_format: SMART_NUMBER
  show_labels: true
  labels_outside: true
  outerRadius: 70
  innerRadius: 30
  extra_form_data: {}
cache_timeout: null
uuid: ab67ab4b-0518-4ce1-9969-eef261919733
version: 1.0.0
dataset_uuid: 1cc68a64-0b9e-42a5-85e7-52571ceaf4ba
