slice_name: "ABC: Стабильность категорий"
description: Доля клиентов, оставшихся в той же товарной категории.
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  adhoc_filters: []
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: values
  contributionMode: null
  datasource: 8__table
  groupby: []
  markerEnabled: false
  metrics:
    - category_stability_percent_avg
  orientation: horizontal
  order_bars: true
  queryFields:
    columns: groupby
    groupby: groupby
    metrics: metrics
  row_limit: 100
  show_extra_controls: false
  show_legend: false
  show_value: false
  stack: null
  truncateXAxis: false
  truncateYAxis: false
  viz_type: echarts_timeseries_bar
  x_axis: first_category
  x_axis_title: Стабильность, %
  x_axis_title_margin: 30
  y_axis_title: Начальная категория
  y_axis_title_margin: 0
  y_axis_format: SMART_NUMBER
  zoomable: false
cache_timeout: null
uuid: 24a6d4cb-999a-44aa-a74c-082936509753
version: 1.0.0
dataset_uuid: 60d26ecb-35a0-43db-be3a-7af1d422d3e4
