slice_name: "Отток: по категориям доставки"
description: Уровень оттока по категориям доставки из notebook.
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  adhoc_filters: []
  bar_stacked: false
  bottom_margin: auto
  color_scheme: supersetColors
  columns: []
  contribution: false
  datasource: 5__table
  groupby:
    - delivery_category
  metrics:
    - churn_rate_pct_avg
  order_bars: true
  queryFields:
    columns: groupby
    groupby: groupby
    metrics: metrics
  row_limit: 100
  show_bar_value: false
  show_controls: true
  show_legend: false
  viz_type: dist_bar
  x_axis_label: Категория доставки
  x_ticks_layout: flat
  y_axis_format: SMART_NUMBER
cache_timeout: null
uuid: e5879788-6434-4bdc-aa26-7ca587234701
version: 1.0.0
dataset_uuid: 6e8cd520-ed7e-4ea1-9884-10df8b2c7fce
