slice_name: "Отток: Доставка vs возвраты"
description: Матрица оттока по категориям доставки и возвратов.
certified_by: null
certification_details: null
viz_type: heatmap_v2
params:
  datasource: 5__table
  viz_type: heatmap_v2
  x_axis: returns_category
  groupby: delivery_category
  metric: churn_rate_pct_avg
  adhoc_filters: []
  row_limit: 10000
  sort_x_axis: alpha_asc
  sort_y_axis: alpha_asc
  normalize_across: heatmap
  legend_type: continuous
  linear_color_scheme: superset_seq_1
  xscale_interval: -1
  yscale_interval: -1
  left_margin: auto
  bottom_margin: auto
  value_bounds:
    - null
    - null
  y_axis_format: SMART_NUMBER
  show_legend: true
  show_percentage: false
  show_values: true
  extra_form_data: {}
cache_timeout: null
uuid: db624baf-069f-479e-bb35-650a9704344e
version: 1.0.0
dataset_uuid: 6e8cd520-ed7e-4ea1-9884-10df8b2c7fce
