slice_name: "ABC: Доля выручки по клиентским категориям"
description: Доля выручки по клиентским ABC-категориям из notebook.
certified_by: null
certification_details: null
viz_type: pie
params:
  datasource: 1__table
  viz_type: pie
  groupby:
    - abc_category
  metric: total_revenue_sum
  adhoc_filters: []
  row_limit: 100
  sort_by_metric: true
  color_scheme: supersetColors
  show_labels_threshold: 5
  show_legend: true
  legendType: scroll
  legendOrientation: top
  label_type: key
  number_format: SMART_NUMBER
  show_labels: true
  labels_outside: true
  outerRadius: 70
  innerRadius: 30
  extra_form_data: {}
cache_timeout: null
uuid: cda1c9fd-70bb-4168-b8cc-f70bbd406140
version: 1.0.0
dataset_uuid: 12e7b948-21e7-4cb2-8d1a-8b078f4d9ca9
