slice_name: "ABC: Доля клиентов по месяцам (%)"
description: Динамика доли клиентов по ежемесячным ABC-категориям.
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  adhoc_filters: []
  bar_stacked: false
  bottom_margin: auto
  color_scheme: supersetColors
  columns: []
  contribution: false
  datasource: 7__table
  groupby:
    - year_month
  metrics:
    - a_percent_avg
    - b_percent_avg
    - c_percent_avg
  order_bars: false
  queryFields:
    columns: groupby
    groupby: groupby
    metrics: metrics
  row_limit: 1000
  show_bar_value: false
  show_controls: true
  show_legend: true
  viz_type: dist_bar
  x_axis_label: Месяц
  x_ticks_layout: staggered
  y_axis_format: SMART_NUMBER
cache_timeout: null
uuid: 48d840b4-368f-4150-981f-89ecf174570e
version: 1.0.0
dataset_uuid: 44ae6479-ec5b-4b98-8bba-bee84cd32daf
