slice_name: "ABC: Топ-15 регионов по выручке"
description: Топ-15 регионов по выручке с ABC-категориями.
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  adhoc_filters: []
  bar_stacked: false
  bottom_margin: auto
  color_scheme: supersetColors
  columns: []
  contribution: false
  datasource: 4__table
  groupby:
    - state
  metrics:
    - total_revenue_sum
  order_bars: true
  queryFields:
    columns: groupby
    groupby: groupby
    metrics: metrics
  row_limit: 15
  show_bar_value: false
  show_controls: true
  show_legend: false
  viz_type: dist_bar
  x_axis_label: Регион
  x_ticks_layout: staggered
  y_axis_format: SMART_NUMBER
cache_timeout: null
uuid: 2d53a12b-2826-4e08-abb2-aa3c82114400
version: 1.0.0
dataset_uuid: 78ff34b0-bc2e-4b7a-9bf1-af0280a772e5
