slice_name: "ABC: Топ-15 регионов по выручке"
description: Топ-15 регионов по выручке с ABC-категориями.
certified_by: null
certification_details: null
viz_type: echarts_timeseries_bar
params:
  adhoc_filters: []
  annotation_layers: []
  color_scheme: supersetColors
  comparison_type: values
  contributionMode: null
  datasource: 4__table
  groupby: []
  markerEnabled: false
  metrics:
    - total_revenue_sum
  orientation: horizontal
  order_bars: true
  queryFields:
    columns: groupby
    groupby: groupby
    metrics: metrics
  row_limit: 15
  show_extra_controls: false
  show_legend: false
  show_value: false
  stack: null
  truncateXAxis: false
  truncateYAxis: false
  viz_type: echarts_timeseries_bar
  x_axis: state
  x_axis_title: Выручка
  x_axis_title_margin: 30
  y_axis_title: Регион
  y_axis_title_margin: 0
  y_axis_format: SMART_NUMBER
  zoomable: false
cache_timeout: null
uuid: 2d53a12b-2826-4e08-abb2-aa3c82114400
version: 1.0.0
dataset_uuid: 78ff34b0-bc2e-4b7a-9bf1-af0280a772e5
