slice_name: "XYZ: Стабильность возвратов"
description: XYZ-распределение клиентов по стабильности возвратов.
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  adhoc_filters:
    - clause: WHERE
      comparator: 0
      expressionType: SIMPLE
      operator: ">"
      operatorId: GREATER_THAN
      sqlExpression: null
      subject: month_count
  bar_stacked: false
  bottom_margin: auto
  color_scheme: supersetColors
  columns: []
  contribution: false
  datasource: 5__table
  groupby:
    - returns_xyz_category
  metrics:
    - count
  order_bars: true
  queryFields:
    columns: groupby
    groupby: groupby
    metrics: metrics
  row_limit: 100
  show_bar_value: false
  show_controls: true
  show_legend: false
  viz_type: dist_bar
  x_axis_label: XYZ возвратов
  x_ticks_layout: flat
  y_axis_format: SMART_NUMBER
cache_timeout: null
uuid: 615b88f9-a69f-4c0a-a0ba-73bee3e68caf
version: 1.0.0
dataset_uuid: 6e8cd520-ed7e-4ea1-9884-10df8b2c7fce
