slice_name: "RFM: Сегменты клиентов"
description: Количество клиентов по RFM-сегментам.
certified_by: null
certification_details: null
viz_type: dist_bar
params:
  adhoc_filters: []
  bar_stacked: false
  bottom_margin: auto
  color_scheme: supersetColors
  columns: []
  contribution: false
  datasource: 2__table
  groupby:
    - segment
  metrics:
    - count
  order_bars: false
  queryFields:
    columns: groupby
    groupby: groupby
    metrics: metrics
  row_limit: 10000
  show_bar_value: false
  show_controls: true
  show_legend: false
  viz_type: dist_bar
  x_axis_label: RFM сегмент
  x_ticks_layout: flat
  y_axis_format: SMART_NUMBER
cache_timeout: null
uuid: 6300eb8a-8700-4aea-ac04-3014ed2a4b40
version: 1.0.0
dataset_uuid: a6c06d30-a390-49ca-885a-0fe0f2e5d081
