slice_name: "RFM: Матрица количества клиентов"
description: Количество клиентов по матрице R и F.
certified_by: null
certification_details: null
viz_type: heatmap_v2
params:
  datasource: 2__table
  viz_type: heatmap_v2
  x_axis: f_score
  groupby: r_score
  metric: count
  adhoc_filters: []
  row_limit: 10000
  sort_x_axis: alpha_asc
  sort_y_axis: alpha_asc
  normalize_across: heatmap
  legend_type: continuous
  linear_color_scheme: superset_seq_1
  xscale_interval: -1
  yscale_interval: -1
  left_margin: auto
  bottom_margin: auto
  value_bounds:
    - null
    - null
  y_axis_format: SMART_NUMBER
  show_legend: true
  show_percentage: false
  show_values: true
  extra_form_data: {}
cache_timeout: null
uuid: 7c459df0-e561-4fdb-a2a0-c29d81984c58
version: 1.0.0
dataset_uuid: a6c06d30-a390-49ca-885a-0fe0f2e5d081
