database_name: Retail Analytics
sqlalchemy_uri: postgresql+psycopg2://bi_readonly:bi_readonly@postgres:5432/retail_analytics
cache_timeout: null
expose_in_sqllab: true
allow_run_async: false
allow_ctas: false
allow_cvas: false
allow_dml: false
allow_file_upload: false
extra:
  metadata_params: {}
  engine_params: {}
  metadata_cache_timeout: {}
  schemas_allowed_for_file_upload: []
uuid: 73e7590d-077a-4c05-a28b-f13d9a3324d1
version: 1.0.0
